spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/mib
    username: mib_admin
    password: password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: false
    user: mib_admin
    password: password
    url: jdbc:postgresql://localhost:5432/mib

logging:
  pattern:
    console: '%-5level %logger{36} - %msg%n'