spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://pg:5432/studs
    username: s207216
    password: trp049
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: false
    user: s207216
    password: trp049
    url: jdbc:postgresql://pg:5432/studs

logging:
  pattern:
    console: '%-5level %logger{36} - %msg%n'